server:
  port: 0

reservation:
  names: Marcin,Paweł,Michał,Julek,Artur,Michał2,Marcin2,Michał3,Jacek,Marek,Wojtek

spring:
  datasource:
    url: jdbc:h2:/tmp/sprio;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false

message: New message from Config Server

management:
  shell:
    ssh:
      enabled: false
